name: Deploy Backend to EC2

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run tests
      # - name: Run tests
      #   run: npm test

      # Build application
      - name: Build project
        run: npm run build

      # Docker login
      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      # Build Docker image
      - name: Build Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/tinyurl-backend:latest .

      # Push Docker image
      - name: Push Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/tinyurl-backend:latest

      # Deploy to EC2
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/tinyurl-backend

            git fetch origin
            git checkout prod
            sudo git reset --hard origin/prod

            docker compose --env-file .env.prod -f docker-compose.prod.yml down

            docker compose --env-file .env.prod -f docker-compose.prod.yml pull

            docker compose --env-file .env.prod -f docker-compose.prod.yml up -d